### ISSUE TITLE
[BUG] Doesn't seem to save transcriptions on Mac

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-skill-dictation#4]
```sh
2024-03-29 13:52:25.707 - audio - ovos_audio.service:execute_tts:344 - INFO - Speak: ok, i am ready for dictation
2024-03-29 13:52:32.129 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file Okay, I am ready for dictation.voc
2024-03-29 13:52:32.131 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file Okay, I am ready for dictation.voc
2024-03-29 13:52:32.132 - skills - ovos_bus_client.apis.gui:_normalize_page_name:392 - WARNING - Deprecation version=0.1.0. Caller=ovos_skill_dictation:101. GUI resources should exclude gui-specific file extensions. This call should probably pass `SYSTEM_TextFrame`, instead of `SYSTEM_TextFrame.qml`
2024-03-29 13:52:39.516 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file This is the first test and what I'd like to ultimately end up doing is make sure that I have this and some other.voc
2024-03-29 13:52:39.518 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file This is the first test and what I'd like to ultimately end up doing is make sure that I have this and some other.voc
2024-03-29 13:52:39.519 - skills - ovos_bus_client.apis.gui:_normalize_page_name:392 - WARNING - Deprecation version=0.1.0. Caller=ovos_skill_dictation:101. GUI resources should exclude gui-specific file extensions. This call should probably pass `SYSTEM_TextFrame`, instead of `SYSTEM_TextFrame.qml`
2024-03-29 13:52:42.257 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file skills available that are specific to work.voc
2024-03-29 13:52:42.258 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file skills available that are specific to work.voc
2024-03-29 13:52:42.259 - skills - ovos_bus_client.apis.gui:_normalize_page_name:392 - WARNING - Deprecation version=0.1.0. Caller=ovos_skill_dictation:101. GUI resources should exclude gui-specific file extensions. This call should probably pass `SYSTEM_TextFrame`, instead of `SYSTEM_TextFrame.qml`
2024-03-29 13:52:50.040 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file Obdictation.voc
2024-03-29 13:52:50.041 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file Obdictation.voc
2024-03-29 13:52:50.042 - skills - ovos_bus_client.apis.gui:_normalize_page_name:392 - WARNING - Deprecation version=0.1.0. Caller=ovos_skill_dictation:101. GUI resources should exclude gui-specific file extensions. This call should probably pass `SYSTEM_TextFrame`, instead of `SYSTEM_TextFrame.qml`
2024-03-29 13:52:56.536 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file Stop dictation.voc
2024-03-29 13:52:56.537 - skills - ovos_workshop.resource_files:_locate:352 - ERROR - Could not find resource file Stop dictation.voc
2024-03-29 13:52:56.539 - skills - ovos_bus_client.apis.gui:_normalize_page_name:392 - WARNING - Deprecation version=0.1.0. Caller=ovos_skill_dictation:101. GUI resources should exclude gui-specific file extensions. This call should probably pass `SYSTEM_TextFrame`, instead of `SYSTEM_TextFrame.qml`
```

**Comment by mikejgray** [comment]
More relevant logs from Dinkum:

```sh
2024-03-29 13:56:57.541 - voice - ovos_dinkum_listener.service:run:324 - ERROR - voice_loop failed
Traceback (most recent call last):
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 320, in run
    self.voice_loop.run()
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_dinkum_listener/voice_loop/voice_loop.py", line 261, in run
    self._before_cmd(chunk)
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_dinkum_listener/voice_loop/voice_loop.py", line 529, in _before_cmd
    self.stt.stream_data(stt_chunk)
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_plugin_manager/templates/stt.py", line 197, in stream_data
    self.queue.put(data)
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'put'
2024-03-29 13:56:57.544 - voice - ovos_dinkum_listener.service:on_error:94 - ERROR - DinkumVoiceService failed to launch ('NoneType' object has no attribute 'put').
2024-03-29 13:56:57.545 - voice - ovos_dinkum_listener.service:run:327 - INFO - Service stopping
2024-03-29 13:56:57.545 - voice - ovos_dinkum_listener.service:on_stopping:98 - INFO - DinkumVoiceService is shutting down...
^CTraceback (most recent call last):
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/bin/ovos-dinkum-listener", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_dinkum_listener/__main__.py", line 25, in main
    service.run()
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 328, in run
    self.stop()
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 394, in stop
    self._shutdown()
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 416, in _shutdown
    self.mic.stop()
  File "/Users/mikegray_1_2/Library/Caches/pypoetry/virtualenvs/ovos-mac-rOfzzh7T-py3.11/lib/python3.11/site-packages/ovos_microphone_plugin_pyaudio/__init__.py", line 76, in stop
    self._thread.join()
  File "/Users/mikegray_1_2/miniconda3/lib/python3.11/threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "/Users/mikegray_1_2/miniconda3/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```
